import { describe, it, expect, beforeEach } from 'vitest'
import {
  serializeNortObject,
  setResourceFromRef,
  parseBooleanWithDefault,
  scaleSliderValue,
  buildCustomizePayload,
  persistCustomizeOverrides,
  loadRandomOverrides,
  loadCustomizeOverrides,
  computeGridOverlayAlpha,
  computeConcentricWaveCount,
} from '../GenerateForm.helpers'

describe('GenerateForm autogenerated deterministic helpers', () => {
  beforeEach(() => {
    localStorage.clear()
  })

  it('setResourceFromRef parses pack|name and ignores falsy', () => {
    const p = {}
    setResourceFromRef(p, 'border', 'pack1|n1')
    expect(p.border).toEqual({ artPack: 'pack1', name: 'n1' })
    const p2 = {}
    setResourceFromRef(p2, 'k', '')
    expect(p2.k).toBeUndefined()
  })

  it('serializeNortObject sorts keys consistently', () => {
    const obj = { b: 2, a: { d: 4, c: 3 } }
    const s = serializeNortObject(obj)
    expect(s.indexOf('"a"') < s.indexOf('"b"')).toBe(true)
  })

  it('parseBooleanWithDefault prefers mergedRef when appropriate', () => {
    const merged = { current: { priorKey: true } }
    expect(parseBooleanWithDefault(false, merged, 'priorKey', false)).toBe(true)
    expect(parseBooleanWithDefault('x', null, 'k', 'x')).toBe(true)
  })

  it('scaleSliderValue maps known slider positions', () => {
    expect(scaleSliderValue(5)).toBeCloseTo(1, 6)
    expect(typeof scaleSliderValue(10)).toBe('number')
  })

  it('buildCustomizePayload and persist/load overrides interact with localStorage', () => {
    const vals = { backgroundType: 'SolidColor', oceanColor: '#abcdef', drawRoads: false }
    const payload = buildCustomizePayload(vals)
    expect(payload.backgroundType).toBe('SolidColor')
    persistCustomizeOverrides(vals)
    const raw = localStorage.getItem('vellaris-customize-overrides')
    expect(raw).toBeTruthy()
    const parsed = loadCustomizeOverrides()
    expect(parsed.backgroundType).toBe('SolidColor')

    localStorage.setItem('vellaris-random-manual-overrides', JSON.stringify({ foo: 'bar' }))
    const r = loadRandomOverrides()
    expect(r.foo).toBe('bar')
  })

  it('computeGridOverlayAlpha and computeConcentricWaveCount basic cases', () => {
    expect(computeGridOverlayAlpha(null, '#010203')).toBe(255)
    expect(computeConcentricWaveCount(5, '')).toBe(5)
    expect(computeConcentricWaveCount(undefined, '2')).toBe(2)
  })
})
